version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"  # MApping the port 8000 from container to port 9001 from host
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory  # Using memory mode to avoid problems with permissions
    networks:
      - my-network

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb:8000  # Usamos el nombre del servicio y el puerto interno
    networks:
      - my-network

networks:
  my-network:
    driver: bridge