version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "9000:8000"  # Mapea el puerto 8000 del contenedor al puerto 9000 del host
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory  # Usamos modo en memoria para evitar problemas de permisos
    environment:
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_REGION=us-east-1
    networks:
      - my-network

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb:8000  # Usamos el nombre del servicio y el puerto interno
    networks:
      - my-network

networks:
  my-network:
    driver: bridge